### ISSUE TITLE
bcrypt isn't compatible with newer versions of node

### ISSUE THREAD

**Issue by dylang** [swennemans/isoose#1]
Hi, I found your project via Github search and it seems to be the starter kit that has everything I'm looking for, except I'm using the latest version of iojs .

bcrypt seems to have problems on the latest versions of node/iojs: https://github.com/ncb000gt/node.bcrypt.js/issues

There seem to be alternatives such as
https://github.com/dcodeIO/bcrypt.js

**Comment by swennemans** [comment]
Ah cool. Thanks for the info. Didn't know that. 

I've swapped the two. Havn't tested the `compare` function yet (from the syntax it looks like it's exactly the same). The `genSalt` function works fine.
